------------------------------------------------------------------------

title: "DIABLO- Breast Cancer subtypes- mRNA-miRNA network: PLOTS"

#IMPORTS

```{r}
library(mixOmics)
library(RColorBrewer)
library(ggtext)
library(ggplot2)
library(dplyr)
```

```{r}
#Set WD

#setwd('C:\\users\\arati\\OneDrive - FCT NOVA\\PBCM')
setwd('C:\\Users\\USER~\\OneDrive - FCT NOVA\\PBCM')
```

#Model load

```{r}
Model = readRDS('C:\\users\\arati\\OneDrive - FCT NOVA\\PBCM\\Model-Ari')
#Model = readRDS('C:\\Users\\USER~\\OneDrive - FCT NOVA\\PBCM\\Model-Ari')
```

```{r}
Data_test = readRDS('C:\\users\\arati\\OneDrive - FCT NOVA\\PBCM\\data.test-Ari')
#Data_test = readRDS('C:\\Users\\USER~\\OneDrive - FCT NOVA\\PBCM\\data.test-Ari')

test.data = readRDS("C:\\Users\\USER~\\OneDrive - FCT NOVA\\PBCM\\data.test.pred-Ari")
```

```{r}
pred = predict(Model, newdata = Data_test)
```

```{r}
confusion_matrix = get.confusion_matrix(truth = test.data$clinical.test$PAM50_SUBTYPE, predicted = pred$WeightedVote$centroids.dist[,2])
```

```{r}
confusion_matrix
```

#Performance Evaluation

```{r}
evaluation_metrics <- function(confusion_mat){
  
  tp_Bsl<- confusion_mat['Basal-like', 'predicted.as.Basal-like']
  tp_Her2<- confusion_mat['HER2-enriched', 'predicted.as.HER2-enriched']
  tp_LumA<- confusion_mat['Luminal A', 'predicted.as.Luminal A']
  tp_LumB<- confusion_mat['Luminal B', 'predicted.as.Luminal B']
  
  fp_Bsl<- sum(confusion_mat[, 'predicted.as.Basal-like']) - tp_Bsl
  fp_Her2<- sum(confusion_mat[, 'predicted.as.HER2-enriched']) - tp_Her2
  fp_LumA<- sum(confusion_mat[, 'predicted.as.Luminal A']) - tp_LumA
  fp_LumB<- sum(confusion_mat[, 'predicted.as.Luminal B']) - tp_LumB
  
  fn_Bsl<- sum(confusion_mat['Basal-like', ]) - tp_Bsl
  fn_Her2<- sum(confusion_mat['HER2-enriched', ]) -  tp_Her2
  fn_LumA<- sum(confusion_mat['Luminal A', ]) - tp_LumA
  fn_LumB<- sum(confusion_mat['Luminal B', ]) - tp_LumB
  
  total = sum(confusion_mat)
  
  tn_Bsl<- total - (tp_Bsl + fp_Bsl + fn_Bsl)
  tn_Her2<- total - (tp_Her2 + fp_Her2 + fn_Her2) 
  tn_LumA<- total - (tp_LumA + fp_LumA + fn_LumA)
  tn_LumB<- total - (tp_LumB + fp_LumB + fn_LumB)
  
  tp<- sum(tp_Bsl, tp_Her2, tp_LumA, tp_LumB)
  tn<- sum(tn_Bsl, tn_Her2, tn_LumA, tn_LumB)
  fp<- sum(fp_Bsl, fp_Her2, fp_LumA, fp_LumB)
  fn<- sum(fn_Bsl, fn_Her2, fn_LumA, fn_LumB)
  
  
  # Calculate accuracy
  accuracy <- (tp+tn) / (tp + tn + fp + fn)
  
  # Calculate precision
  precision <- tp / (tp+fp)
  
  # Calculate recall
  recall <- tp / (tp+fn)
  
  # Calculate F1
  f1 <- 2 * (precision*recall) / (precision+recall)
  
  metrics <- list( 'accuracy' = accuracy,
                   'precision' = precision,
                   'recall' = recall,
                   'F1' = f1)
  return(metrics)
}
```

```{r}
evaluation_metrics(confusion_matrix)
```

```{r}
get.BER(confusion_matrix)
```

#Plots 

##ROC Curve

```{r}
#ROC curve- miRNA
auc.splsda = auroc(Model, roc.block = "miRNA", 
                   roc.comp = 2, print = FALSE)
```

```{r}
#ROC curve- mRNA
auc.splsda = auroc(Model, roc.block = "mRNA", 
                   roc.comp = 2, print = FALSE)
```

##PlotIndiv

```{r}
plotIndiv(Model, ind.names = FALSE, legend = TRUE, 
          title = 'DIABLO Plots')
```

##Loadings

```{r}
#Loadings- Component 1

plotLoadings(final.diablo.model, comp = 1, contrib = 'max', method = 'median')
```

```{r}
#Loadings- Component 2

plotLoadings(final.diablo.model, comp = 2, contrib = 'max', method = 'median')
```

##Circus Plot- Correlations

```{r}
#cutoff = 0.5

circosPlot(Model, cutoff = 0.5, line = TRUE,
           color.Y = c('pink', 'lightblue', 'yellow', 'orange'),
           color.blocks= c('yellow2', 'magenta3'),
           color.cor = c("red2","dodgerblue1"), size.labels = 1.5)
```

```{r}
#cutoff = 0.6

circosPlot(Model, cutoff = 0.6, line = TRUE,
           color.Y = c('pink', 'lightblue', 'yellow', 'orange'),
           color.blocks= c('yellow2', 'magenta3'),
           color.cor = c("red2","dodgerblue1"), size.labels = 1.5)
```

```{r}
#cutoff = 0.7

circosPlot(Model, cutoff = 0.7, line = TRUE,
           color.Y = c('pink', 'lightblue', 'yellow', 'orange'),
           color.blocks= c('yellow2', 'magenta3'),
           color.cor = c("red2","dodgerblue1"), size.labels = 1.5)
```


```{r}
#cutoff = 0.75

circosPlot(Model, cutoff = 0.75, line = TRUE,
           color.Y = c('pink', 'lightblue', 'yellow', 'orange'),
           color.blocks= c('yellow2', 'magenta3'),
           color.cor = c("red2","dodgerblue1"), size.labels = 1.5)
```

```{r}
#cutoff = 0.8

circosPlot(Model, cutoff = 0.8, line = TRUE,
           color.Y = c('pink', 'lightblue', 'yellow', 'orange'),
           color.blocks= c('yellow2', 'magenta3'),
           color.cor = c("red2","dodgerblue1"), size.labels = 1.5)

#png('cicrosPlot-cutoff 08.png')
pdf('cicrosPlot-cutoff 08.pdf')
circosPlot(Model, cutoff = 0.8, line = TRUE,
           color.Y = c('pink', 'lightblue', 'yellow', 'orange'),
           color.blocks= c('yellow2', 'magenta3'),
           color.cor = c("red2","dodgerblue1"), size.labels = 1.5)
dev.off()
```

```{r}
#cutoff = 0.9

circosPlot(Model, cutoff = 0.9, line = TRUE,
           color.Y = c('pink', 'lightblue', 'yellow', 'orange'),
           color.blocks= c('yellow2', 'magenta3'),
           color.cor = c("red2","dodgerblue1"), size.labels = 1.5)
```

Extract data from chosen circus plot

```{r}
#Comp 1

circos_data <- circosPlot(Model, cutoff = 0.7, comp = 1)
write.csv(circos_data, "Circ_Plot_Covariance_Features_Comp1.csv", row.names = T)
```

```{r}
#Comp2

circos_data <- circosPlot(Model, cutoff = 0.7, comp = 2)
write.csv(circos_data, "Circ_Plot_Covariance_Features_Comp2.csv", row.names = T)
```

## Heatmap
```{r}
cimDiablo(del)
```
